#:schema node_modules/wrangler/config-schema.json
name = "sub-converter"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4000611b0f424b20a32cefbb7bf5e063" }
]
